name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
  runs-on: ubuntu-latest
   env:
      PATH_TEST_PROJECT: ./
      
  steps:
    - name: Setup test in the .NET Core project
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 7.0.302
    - name: Running tests
    - run: dotnet test ${{ env.PATH_TEST_PROJECT }} --verbosity minimal
    
  build:
    env:
      PATH_WEBAPP_PROJECT: ./
      #PATH_WEBAPP_AZURE_PROJECT: 
    runs-on: ubuntu-latest
    steps:
      - name: Setup build in the .NET Core project
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.302
      - name: Running tests
      - run: dotnet test ${{ env.PATH_TEST_PROJECT }} --verbosity minimal
  # deploy:
  #   name: Deploy Azure
  #   needs: [coverage, build]

  #   runs-on: ubuntu-lates
      # - name: Publish com o utilitario dotnet
      #   run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBAPP }} -c Release -o app

      # - name: Login no Azure
      #   uses: Azure/login@v1.1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deployment no Azure App Service
      #   uses: Azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.NOME_WEBAPP_AZURE }}
      #     package: "./app"

      # - name: Notificação de sucesso na execução
      #   if: success()
      #   shell: pwsh
      #   run: |
      #     $Execucao = '{ "workflow": "' + ${env:GITHUB_WORKFLOW} + '", "numExecucao": ' + ${env:GITHUB_RUN_NUMBER} + ' }'
      #     Write-Host $Execucao
      #     Invoke-RestMethod -Uri "${{ secrets.URL_LOGIC_APP_SUCESSO }}" -Method POST -ContentType "application/json" -Body $Execucao

      # - name: Notificação de erro na execução
      #   if: failure()
      #   shell: pwsh
      #   run: |
      #     $Execucao = '{ "workflow": "' + ${env:GITHUB_WORKFLOW} + '", "numExecucao": ' + ${env:GITHUB_RUN_NUMBER} + ' }'
      #     Write-Host $Execucao
      #     Invoke-RestMethod -Uri "${{ secrets.URL_LOGIC_APP_FALHA }}" -Method POST -ContentType "application/json" -Body $Execucao
