name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES: ./
      CAMINHO_PROJETO_WEBAPP: ./
      NOME_WEBAPP_AZURE: todoapi

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [7.0.302]

    steps:
      - uses: actions/checkout@v3

      - name: Listar versões do .NET pré-instaladas
        run: dotnet --list-sdks

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build com o utilitario dotnet
        run: dotnet build ${{ env.CAMINHO_PROJETO_WEBAPP }} --configuration Release

  coverage:
    env:
      CAMINHO_PROJETO_TESTES: ./
      CAMINHO_PROJETO_WEBAPP: ./
      NOME_WEBAPP_AZURE: todoapi

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [7.0.302]

    steps:
      - uses: actions/checkout@v3

      - name: Listar versões do .NET pré-instaladas
        run: dotnet --list-sdks

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Executar testes automatizados
        run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

  deploy:
    name: Deploy Azure
    needs: [coverage, build]
    env:
      CAMINHO_PROJETO_TESTES: ./
      CAMINHO_PROJETO_WEBAPP: ./
      NOME_WEBAPP_AZURE: todoapi

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [7.0.302]

    steps:
      - uses: actions/checkout@v3

      - name: Listar versões do .NET pré-instaladas
        run: dotnet --list-sdks

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Executar testes automatizados
        run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal
